version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    ignore:
      - dependency-name: "go"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    groups:
      actions-updates:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/build/docker/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    groups:
      docker-updates:
        patterns:
          - "*"
