version: 2

project_name: rcon-cli

before:
  hooks:
    - go mod tidy

builds:
  - id: rcon
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - 386
    ignore:
      - goos: darwin
        goarch: 386
    main: ./cmd/gorcon/main.go
    binary: rcon
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - rcon.yaml

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

dockers:
  - id: rcon-amd64
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/dmirtillo/rcon-cli:{{ .Version }}-amd64"
    dockerfile: build/docker/Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
  - id: rcon-arm64
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/dmirtillo/rcon-cli:{{ .Version }}-arm64"
    dockerfile: build/docker/Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: ghcr.io/dmirtillo/rcon-cli:{{ .Version }}
    image_templates:
      - ghcr.io/dmirtillo/rcon-cli:{{ .Version }}-amd64
      - ghcr.io/dmirtillo/rcon-cli:{{ .Version }}-arm64
  - name_template: ghcr.io/dmirtillo/rcon-cli:latest
    image_templates:
      - ghcr.io/dmirtillo/rcon-cli:{{ .Version }}-amd64
      - ghcr.io/dmirtillo/rcon-cli:{{ .Version }}-arm64

release:
  github:
    owner: dmirtillo
    name: rcon-cli
